spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:competition@competition.mvoos.mongodb.net/competition_db?retryWrites=true&w=majority
      authentication-database: admin
      database: competition_db
server:
  port: 8080
competition:
  jwtSecret: ${SPRING_JWT}
  jwtExpirationMs: 86400000