spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:competition@competition.mvoos.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      authentication-database: admin
      database: tuziemiec_db
server:
  port: 8080